### PR TITLE
WDP210602-15

### PR DESCRIPTION
**Pull request by Magdalena-Tarka**
_WDP210602-15 RWD - topbar i banner_

Dodałam responsywnośc do komponentów TopBar i CompanyClaim.
TopBar: w mobile rozdzielczościach elementy po prawej stronie tzn login i register są bez tekstu.
CompanyClaim: w mobile rozdzielczościach logo jest po lewej stronie, po prawej natomiast koszyk, a pod nim nr telefonu, wszystkie element zostały wyrównane w poziomie.

### CODE REVIEW

**Review by Varenthein — CHANGES_REQUESTED** [review]
I think you should do something about the cart :)

image

**Comment by Magdalena-Tarka** [comment]
Dear PM, ofc I will change whatever PM will expect:) but please let me know what exactly do you mean?
Yes, I agree with you that on xs screens it looks packed, what I suggest is to make logo a bit higher to meet cart level and decrease its size. In my opinion right-aligned cart presents good.
You can find bellow the result of my correction, please let me know if its ok for you.
image

**Comment by Varenthein** [comment]
> Dear PM, ofc I will change whatever PM will expect:) but please let me know what exactly do you mean?
> Yes, I agree with you that on xs screens it looks packed, what I suggest is to make logo a bit higher to meet cart level and decrease its size. In my opinion right-aligned cart presents good.
> You can find bellow the result of my correction, please let me know if its ok for you.
> image

I don't expect anything special. I just don't want the amount of the product in the cart to leave the box :)

image

**Comment by Varenthein** [comment]
image

It won't compile...

**Pull request merged**
